apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc
  namespace: ceph-csi-cephfs
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cephfs-sc
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo
  namespace: ceph-csi-cephfs
spec:
  containers:
    - name: demo-container
      image: busybox
      command: ["sh", "-c", "echo 'Hello CEPHFS' > /mnt/cephfs/data.txt && sleep 3600"]
      volumeMounts:
        - name: cephfs-claim
          mountPath: /mnt/cephfs
      
  volumes:
    - name: cephfs-claim
      persistentVolumeClaim:
        claimName: cephfs-pvc